name: Deploy AWS Lambda
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build and push to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
          cache: npm

      - name: Install
        run: npm ci

      - name: deploy
        run: |
          npx ncc build src/index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=lambdaName --zip-file=fileb://deploy.zip
